name: food_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  get: ^4.6.1
  google_fonts: 2.3.1
  fancy_shimmer_image: ^2.0.2
  flutter_slidable: ^1.3.0
  bottom_navy_bar: ^6.0.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  google_maps_flutter: ^2.1.8
  geocoding: ^2.0.4
  geolocator: ^9.0.0
  text_scroll: ^0.0.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
